config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path=>'',
                     :path_names=>{:sign_in => 'login', :sign_out => 'logout', :edit=>'profile'},
                     :controllers=> { registrations: 'registrations',
                                      :confirmations => 'confirmations',
                                      :omniauth_callbacks => 'omniauth_callbacks'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :users, only: [:show]
  resources :rooms, path: 'annonces' do
    resources :reservations, only: [:create]
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get 'your_trips' => 'reservations#your_trips', path: 'mes_voyages'
  get 'your_reservations' => 'reservations#your_reservations', path: 'mes_reservations'
  get '/search' => 'pages#search'
  get '/cgu' => 'pages#cgu'
end

app/views/pages/cgu.html.erb
<div class="container">

<div class="row">
  <div class="col-md-12">
    <h3 class="text-center">Politique modèle de confidentialité.</h3>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-12 pull-left">
    <h4>Introduction</h4>
  </div>
  <div class="col-md-12">
    <p>Cette application a pour but de démontrer mes capacitités en développement à de potentiels recruteurs.
       Cette application n'a aucun but commercial. Devant le développement des nouveaux outils de communication, il est nécessaire de porter une attention particulière à la protection de la vie privée. C'est pourquoi, nous nous engageons à respecter la confidentialité des renseignements personnels que nous collectons.
    </p>
  </div>
  <div class="col-md-12 pull-left">
    <h4>Collecte des renseignements personnels</h4>
      <p>Nous collectons les renseignements suivants :</p>
      <ul>
        <li>Nom</li>
        <li>Prénom</li>
        <li>Adresse postale</li>
        <li>Adresse électronique</li>
      </ul>
      <p>Les renseignements personnels que nous collectons sont recueillis au travers de formulaires et grâce à
        l'interactivité établie entre vous et notre site Web. Nous utilisons également, comme indiqué dans la
        section suivante, des fichiers témoins et/ou journaux pour réunir des informations vous concernant.
      </p>
  </div>
  <div class="col-md-12 pull-left">
    <h4>Formulaires  et interactivité</h4>
    <p>Vos renseignements personnels sont collectés par le biais de formulaire, à savoir :</p>
    <ul>
      <li>Formulaire d'inscription au site Web</li>
      <li>Formulaire de création d'une annonce</li>
    </ul>
    <p>Nous utilisons les renseignements ainsi collectés pour les finalités suivantes :</p>
    <ul>
      <li>Localiser les annonces proches de chez vous</li>
      <li>Correspondance</li>
      <li>Commentaires</li>
    </ul>
  </div>
  <div class="col-md-12 pull-left">
    <h4>Droit d'opposition et de retrait</h4>
    <p>
    Nous nous engageons à vous offrir un droit d'opposition et de retrait quant à vos renseignements personnels.
    Le droit d'opposition s'entend comme étant la possiblité offerte aux internautes de refuser que leurs renseignements personnels soient utilisées à certaines fins mentionnées lors de la collecte.
    Le droit de retrait s'entend comme étant la possiblité offerte aux internautes de demander à ce que leurs renseignements personnels ne figurent plus, par exemple, dans une liste de diffusion.
    Pour pouvoir exercer ces droits, vous pouvez :
    <ul>
      <li>Courriel : jordan.bultez@gmail.com</li>
    </ul>
    </p>
  </div>
  <div class="col-md-12 pull-left">
    <h4>Droit d'accès</h4>
    <p>Nous nous engageons à reconnaître un droit d'accès et de rectification aux personnes concernées désireuses de consulter, modifier, voire radier les informations les concernant.
    L'exercice de ce droit se fera :</p>
      <ul>
        <li>Courriel : jordan.bultez@gmail.com</li>
      </ul>
  </div>
  <div class="col-md-12 pull-left">
    <h4>Sécurité</h4>
    <p>Les renseignements personnels que nous collectons sont conservés dans un environnement sécurisé. Les personnes travaillant pour nous sont tenues de respecter la confidentialité de vos informations.
    Pour assurer la sécurité de vos renseignements personnels, nous avons recours aux mesures suivantes :</p>
    <ul>
      <li>Protocole SSL (Secure Sockets Layer)</li>
      <li>Gestion des accès - personne autorisée</li>
      <li>Gestion des accès - personne concernée</li>
      <li>Identifiant / mot de passe</li>
    </ul>
    <p>Nous nous engageons à maintenir un haut degré de confidentialité en intégrant les dernières innovations
       technologiques permettant d'assurer la confidentialité de vos transactions. Toutefois,
       comme aucun mécanisme n'offre une sécurité maximale, une part de risque est toujours présente
       lorsque l'on utilise Internet pour transmettre des renseignements personnels.
     </p>
  </div>
</div>

</div>
<br>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-md-12">
      <h2 class="text-center">Réservez des logements uniques et vivez votre destination comme un habitant.</h2>
  </div>
</div>

<br>

<%= form_tag search_path, method: :get do %>
  <div class="row">
    <div class="col-md-6">
      <%= text_field_tag :search, params[:search], placeholder: "Où? Desination, ville, adresse", class: "form-control"%>
    </div>
    <div class="col-md-2">
      <%= text_field_tag :start_date, params[:start_date], placeholder: "Arrivée", class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= text_field_tag :end_date, params[:end_date], placeholder: "Départ", class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= submit_tag "Rechercher", class:'btn btn-primary' %>
    </div>
  </div>
<%end%>

<br>
<hr>
<br>

<div class="row">
  <div class="col-md-4">
    <h4>Logements</h4>
  </div>
</div>

<div class="row">
  <% @rooms.each do |room| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
        </div>
        <div class="panel-body">
          <p class="home-link">
            <b><%= link_to room.price, room_path(room)%> € - <%= link_to room.room_type, room_path(room) %> - <%= link_to pluralize(room.bed_room, "lit"), room_path(room) %></b>
            <br> <%= link_to room.listing_name, room_path(room) %>
          </p>
        </div>
      </div>
    </div>
  <%end%>
</div>

    <%= render 'layouts/footer'%>

<script type="text/javascript">
  $(function(){
    $('#start_date').datepicker({
        dateFormat: 'dd-mm-yy',
        monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
        'Septembre','Octobre','Novembre','Décembre'],
        dayNamesMin: ['D','L','M','M','J','V','S'],
        minDate: 0,
        maxDate: '3m',
        onSelect: function(selected) {
            var newdate = new Date($("#reservation_start_date").datepicker("getDate"));
            newdate.setDate(newdate.getDate() + 1);
            $('#end_date').datepicker("option","minDate", newdate);
  }
});
$('#end_date').datepicker({
    dateFormat: 'dd-mm-yy',
    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
    'Septembre','Octobre','Novembre','Décembre'],
    dayNamesMin: ['D','L','M','M','J','V','S'],
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
        $('#start_date').datepicker("option", "maxDate", selected);
      }
    });
})
</script>

app/views/pages/search.html.erb
<div class="row">
<div class="col-md-12" id="wrapper">
  <div class="col-md-8" id="article">
    <div class="row">
      <div class="col-md-12">
        <%= search_form_for @search, url: search_path do |f|%>
        <div class="row">
          <div class="col-md-3">
            <%= text_field_tag :start_date, params[:start_date], placeholder: "Arrivée", class: "form-control" %>
          </div>
          <div class="col-md-3">
            <%= text_field_tag :end_date, params[:end_date], placeholder: "Départ", class: "form-control" %>
          </div>
          <div class="col-md-3">
            <%= f.text_field :price_gteq, placeholder: "Prix min", class: "form-control" %>
          </div>
          <div class="col-md-3">
            <%= f.text_field :price_lteq, placeholder: "Prix max", class: "form-control" %>
          </div>
        </div>

        <hr>
        <div class="row">
          <div class="col-md-4">
            <%= check_box_tag "q[room_type_eq_any][]","Logement entier"%> Logement entier
          </div>
          <div class="col-md-4">
            <%= check_box_tag "q[room_type_eq_any][]","Chambre privée"%> Chambre privée
          </div>
          <div class="col-md-4">
            <%= check_box_tag "q[room_type_eq_any][]","Chambre partagée"%> Chambre partagée
          </div>
        </div>

        <hr>
        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Nombre de personnes ?</label>
              <%= f.select :accomodate_gteq, [["1 Personne",1],["2 Personnes",2],["3 Personnes",3],["3 Personnes",3],["4 Personnes",4],["5 Personnes",5],["6 Personnes",6]], prompt:"A séléctionner", class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Nombre de chambres ?</label>
              <%= f.select :bed_room_gteq, [["1",1],["2",2],["3",3],["4",4]], prompt:"A séléctionner", class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Nombre de salles de bain ?</label>
              <%= f.select :bath_room_gteq, [["1",1],["2",2],["3",3],["4",4]], prompt:"A séléctionner", class: "form-control" %>
            </div>
          </div>
        </div>

        <hr>

        <div class="row">
          <div class="col-md-4">
            <%= check_box_tag "q[is_wifi_eq]", true %> Wifi
          </div>
          <div class="col-md-4">
            <%= check_box_tag "q[is_tv_eq]", true %> Télévision
          </div>
          <div class="col-md-4">
            <%= check_box_tag "q[is_closet_eq]", true %> Penderie
          </div>
          <div class="col-md-4">
            <%= check_box_tag "q[is_shampoo_eq]", true %> Shampoing
          </div>
          <div class="col-md-4">
            <%= check_box_tag "q[is_kitchen_eq]", true %> Cuisine
          </div>
          <div class="col-md-4">
            <%= check_box_tag "q[is_heating_eq]", true %> Chauffage
          </div>
          <div class="col-md-4">
            <%= check_box_tag "q[is_air_eq]", true %> Climatisation
          </div>
        </div>

        <br>

        <div class="row">
          <%= f.submit "Rechercher", class: "btn btn-primary"%>
        </div>
        <%end%>

        <hr>

        <div class="row">
          <% if @arrRooms.empty? %>
            Aucune annonce ne correspond à votre recherche.
          <%else%>
          <% @arrRooms.each do |room| %>
            <div class="col-md-4">
              <div class="panel panel-default">
                <div class="panel-heading preview">
                  <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
                </div>
                <div class="panel-body">
                  <%= image_tag avatar_url(room.user), class:"img-circle avatar-small" %>
                  <%= link_to room.listing_name, room %>
                </div>
              </div>
            </div>
          <%end%>
        </div>
        <%end%>
      </div>
    </div>
  </div>
  <div class="col-md-4"id="sidebar">
    <div id="widget">
      <script>
        function initMap() {
          <% if @arrRooms.length > 0 %>
          var uluru = {lat: <%= @arrRooms[0].latitude%>, lng: <%= @arrRooms[0].longitude %>};
          var map = new google.maps.Map(document.getElementById('widget'), {
            zoom: 13,
            center: uluru
          });
          <% else %>
          var uluru = {lat: 48.866667, lng: 2.33333};
          var map = new google.maps.Map(document.getElementById('widget'), {
            zoom: 4,
            center: uluru
          });
          <% end %>

          <% @arrRooms.each do |room| %>
            var marker = new google.maps.Marker({
              position: {lat: <%= room.latitude %>, lng: <%= room.longitude %>},
              map: map,
              title: "<%= room.listing_name %>"
            });
          <%end%>

        }
      </script>
      <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCaKGMeIOYwHY2dv-bH1uqO06wo0e8k4-Q&callback=initMap">
      </script>
    </div>
  </div>
</div>
</div>
<script type="text/javascript">
  $(function(){
    $('#start_date').datepicker({
        dateFormat: 'dd-mm-yy',
        monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
        'Septembre','Octobre','Novembre','Décembre'],
        dayNamesMin: ['D','L','M','M','J','V','S'],
        minDate: 0,
        maxDate: '3m',
        onSelect: function(selected) {
            var newdate = new Date($("#start_date").datepicker("getDate"));
            newdate.setDate(newdate.getDate() + 1);
            $('#end_date').datepicker("option","minDate", newdate);
  }
});
$('#end_date').datepicker({
    dateFormat: 'dd-mm-yy',
    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
    'Septembre','Octobre','Novembre','Décembre'],
    dayNamesMin: ['D','L','M','M','J','V','S'],
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
        $('#start_date').datepicker("option", "maxDate", selected);
      }
    });
})
</script>

<script type="text/javascript">
  $(document).ready(function(){
    $("#sidebar").stick_in_parent({offset_top: 20});
  });
</script>